# Generated by Django 2.2 on 2020-01-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Bed'), ('D', 'Dining'), ('L', 'living'), ('K', 'kids'), ('KI', 'kitchen'), ('D', 'decor')], max_length=2),
        ),
    ]
