# Generated by Django 2.2 on 2020-01-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
    ]
