# Generated by Django 2.2 on 2020-01-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200113_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
    ]
