# Generated by Django 2.2 on 2020-01-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200113_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(default='P', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.CharField(default='S', max_length=100),
            preserve_default=False,
        ),
    ]
