# Generated by Django 2.2 on 2020-01-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kidssection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kidssection',
        ),
    ]
