# Generated by Django 2.2 on 2020-01-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200113_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('datemonth', models.CharField(max_length=2)),
                ('dateday', models.CharField(max_length=2)),
                ('dateyear', models.CharField(max_length=4)),
                ('timehour', models.CharField(max_length=2)),
                ('timemin', models.CharField(max_length=2)),
            ],
        ),
    ]
