# Generated by Django 2.2 on 2020-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ampm',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
