# Generated by Django 2.2 on 2020-01-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userdata_ampm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdata',
            new_name='Appointments',
        ),
    ]
