# Generated by Django 2.2 on 2020-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200114_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='storename',
            field=models.CharField(default='S', max_length=20),
            preserve_default=False,
        ),
    ]
