# Generated by Django 2.2 on 2020-01-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appointments_storename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
