# Generated by Django 2.2 on 2020-01-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Bed'), ('DI', 'Dining'), ('L', 'Living'), ('K', 'Kids'), ('KI', 'Kitchen'), ('D', 'Decor')], max_length=2),
        ),
    ]
